[package]
name = "champ_core"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml_ng = { workspace = true }

[lints.rust]
unused_parens = "allow"

[lints.clippy]
double_parens = "allow"
needless_return = "allow"
