[package]
name = "champ_py"
version.workspace = true
edition.workspace = true

[lib]
name = "champ_rs"
crate-type = ["cdylib"]

[dependencies]
champ_core = { path = "../core" }
serde_json = { workspace = true }
pyo3 = { version = "0.29", features = ["extension-module"] }

[lints.rust]
unused_parens = "allow"

[lints.clippy]
double_parens = "allow"
needless_return = "allow"
